sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_4342ff8d4492_key -iv $encrypted_4342ff8d4492_iv -in multi-k8s-349112-ff89ec2f3978.json.enc -out multi-k8s-349112-ff89ec2f3978.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-349112-ff89ec2f3978.json
  - gcloud config set project multi-k8s-349112
  - gcloud config set compute/zone europe-central2
  - glocud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t valtrenta/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true valtrenta/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master